import React, {
  useState,
  useCallback
} from 'react';
import PropTypes from 'prop-types';
import Swiper from 'react-id-swiper';
import FsLightbox from 'fslightbox-react';
import { useInView } from 'react-intersection-observer';

const PagePortfolioSingleContent = ({
  content
}) => {
  /**
   *
   * @name swiper
   * @type {object}
   */
  const [swiper, updateSwiper] = useState(null);

  const params = {
    lazyLoading: true,
    preloadImages: true,
    shouldSwiperUpdate: true,
    updateOnImagesReady: true,
    loop: true,
    pagination: {
      el: '.swiper-pagination',
      clickable: true
    }
  };

  /**
   *
   * @name goNext
   * @type {function}
   */
  const goNext = () => {
    if (swiper !== null) {
      swiper.slideNext();
    }
  };

  /**
   *
   * @name goPrev
   * @type {function}
   */
  const goPrev = () => {
    if (swiper !== null) {
      swiper.slidePrev();
    }
  };

  const [lightboxController, setLightboxController] = useState({
    toggler: false,
    slide: 1
  });

  /**
   * @description Hook that is generated by the useInView function from the
   *              react-intersection-observer library.
   *
   */
  const [sliderNavRef, inView] = useInView({
    threshold: 1,
    rootMargin: '-150px'
  });

  const openLightboxOnSlide = useCallback((e, index) => {
    e.preventDefault();
    setLightboxController({
      toggler: !lightboxController.toggler,
      slide: index
    });
    if (swiper !== null) {
      swiper.slideTo(index);
    }
  }, [lightboxController.toggler, swiper]);

  return content.projectScreenshots.length && (
    <section className="PagePortfolioSingleContent Page__section Page__section--darkFull">
      <div className="Page__sectionInner grid">
        { content.projectScreenshots.length && (
        <div className="PagePortfolioSingleContent__sliderWrap">
          <div className="PagePortfolioSingleContent__screenshotOuter">
            <div className="PagePortfolioSingleContent__screenshotInner">
              <Swiper
                getSwiper={ updateSwiper }
                { ...params }
              >
                { content.projectScreenshots.map((item, index) => (
                  <a
                    href={ item.add_screenshot.url }
                    key={ item.add_screenshot.id }
                    onClick={ e => openLightboxOnSlide(e, index + 1) }
                    className="PagePortfolioSingleContent__slide"
                  >
                    <img
                      src={ item.add_screenshot.sizes.fullWidth1800_2x }
                      srcSet={ `${item.add_screenshot.sizes.fullWidth1800_2x}, ${item.add_screenshot.sizes.fullWidth1800_2x} 2x` }
                      alt={ item.add_screenshot.alt }
                    />
                  </a>
                ))}
              </Swiper>
            </div>
          </div>
          { content.projectScreenshots.length && (
          <FsLightbox
            toggler={ lightboxController.toggler }
            type="image"
            sources={ content.projectScreenshots.map(item => item.add_screenshot.url) }
            slide={ lightboxController.slide }
          />
          ) }
        </div>
        )}
      </div>
      <div
        ref={ sliderNavRef }
        className={ `Slider__directionNav${inView ? ' Slider__directionNav--active' : ''}` }
      >
        <button
          type="button"
          onClick={ goPrev }
          className="Slider__prev"
        >
            Previous
        </button>
        <button
          type="button"
          onClick={ goNext }
          className="Slider__next"
        >
            Next
        </button>
      </div>
    </section>
  );
};

PagePortfolioSingleContent.propTypes = {
  content: PropTypes.object
};

export default PagePortfolioSingleContent;
