version: "3"
services:
  ui:
    build:
      context: .
    volumes:
      - "./webpack.client.js:/usr/src/app/webpack.client.js"
      - "./webpack.server.js:/usr/src/app/webpack.server.js"
      - "./postcss.config.js:/usr/src/app/postcss.config.js"
      - "./src/:/usr/src/app/src"
      - /usr/src/app/node_modules/
    ports:
      - "3000:3000"
