version: "3"
services:
  ui:
    depends_on:
      - wordpress
    build:
      context: ./ui/
    volumes:
      - "./ui/webpack.client.js:/usr/src/app/webpack.client.js"
      - "./ui/webpack.server.js:/usr/src/app/webpack.server.js"
      - "./ui/postcss.config.js:/usr/src/app/postcss.config.js"
      - "./ui/src/:/usr/src/app/src"
      - /usr/src/app/node_modules/
    ports:
      - "8080:8080"
