import React from 'react';
import { useInView } from 'react-intersection-observer';
import { LazyLoadProps } from './LazyLoad.types';

/**
 * LazyLoad Component
 */
const LazyLoad: React.FC<LazyLoadProps> = ({ children }) => {
  /**
   * Hook that is generated by the useInView function from the
   * react-intersection-observer library.
   */
  const [lazyRef, inView] = useInView({
    threshold: 0,
    rootMargin: '500px',
    triggerOnce: true,
  });

  return (
    <div className="LazyLoad" ref={lazyRef}>
      {inView && children}
    </div>
  );
};

export default LazyLoad;
