import React from 'react';
import PropTypes from 'prop-types';
import { useInView } from 'react-intersection-observer';

/**
 * LazyLoad Component
 *
 * @name LazyLoad
 * @param  {boolean} props.isNew
 */
const LazyLoad = ({
  children
}) => {
  /**
   * @description Hook that is generated by the useInView function from the
   *              react-intersection-observer library.
   *
   */
  const [lazyRef, inView] = useInView({
    threshold: 0,
    rootMargin: '500px',
    triggerOnce: true
  });

  return (
    <div className="LazyLoad" ref={ lazyRef }>
      { inView && children}
    </div>
  );
};

LazyLoad.propTypes = {
  children: PropTypes.any
};

export default LazyLoad;
